# Generated by Django 2.2.4 on 2019-08-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
    ]
